### ISSUE TITLE
ams-pg-test.ooni.org: unexpected control failure

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#1170]
Tests are failing. The culprit seems the web-connectivity test helper at ams-pg-test.ooni.org. Minimal evidence:

```
% ./miniooni --probe-services https://ams-pg-test.ooni.org --input http://www.example.com web_connectivity
[...]
[      0.628468] <info> [1/1] running with input: http://www.example.com
[      0.628567] <info> dnslookup://www.example.com...
[      0.630744] <info> dnslookup://www.example.com... <nil>
[      0.630803] <info> control http://www.example.com...
[      0.707735] <info> control http://www.example.com... dns_nxdomain_error
[...]
```

Full output:

<details>
```
% ./miniooni --probe-services https://ams-pg-test.ooni.org --input http://www.example.com web_connectivity
[      0.000405] <info> miniooni home directory: $HOME/.miniooni
[      0.000916] <info> Looking up OONI backends; please be patient...
[      0.360958] <info> session: using probe services: {Address:https://ams-pg-test.ooni.org Type:https Front:}
[      0.361005] <info> Looking up your location; please be patient...
[      0.500426] <info> - country: IT
[      0.500470] <info> - network: Vodafone Italia S.p.A. (AS30722)
[      0.500487] <info> - resolver's IP: 91.80.36.88
[      0.500500] <info> - resolver's network: Vodafone Italia S.p.A. (AS30722)
[      0.628416] <info> ReportID: 20210107T134350Z_webconnectivity_IT_30722_n1_oFseANDAoINaN3jW
[      0.628468] <info> [1/1] running with input: http://www.example.com
[      0.628567] <info> dnslookup://www.example.com...
[      0.630744] <info> dnslookup://www.example.com... <nil>
[      0.630803] <info> control http://www.example.com...
[      0.707735] <info> control http://www.example.com... dns_nxdomain_error
[      0.707778] <info> DNS analysis result: nil
[      0.823847] <info> TCP/TLS endpoints: 1/2 reachable
[      0.823931] <info> GET http://www.example.com...
[      1.055816] <info> GET http://www.example.com... <nil>
[      1.055863] <info> BodyLengthMatch: nil
[      1.055880] <info> BodyProportion: 0
[      1.055889] <info> StatusCodeMatch: nil
[      1.055896] <info> HeadersMatch: nil
[      1.055906] <info> TitleMatch: nil
[      1.055919] <info> Blocking: nil
[      1.055930] <info> Accessible: nil
[      1.056975] <info> submitting measurement to OONI collector; please be patient...
[      1.183010] <info> saving measurement to disk
[      1.186816] <info> experiment: recv   2 kbyte, sent   6 kbyte
[      1.187684] <info> sessionresolver: failure rate: primary: 1/2; fallback: 1/1
[      1.188090] <info> whole session: recv   7 kbyte, sent   8 kbyte
```
</details>

**Comment by bassosimone** [comment]
From the JSON measurement:

```JSON
  "test_helpers": {
    "backend": {
      "address": "https://test-helper.ooni.org",
      "type": "https"
    }
  }
```

Using this specific test helper yields:

```
% ./oohelper -debug -server https://test-helper.ooni.org -target http://www.example.com
2021/01/07 14:53:32 debug resolve www.example.com...
2021/01/07 14:53:32 debug resolve www.example.com... ([93.184.216.34 2606:2800:220:1:248:1893:25c8:1946], <nil>) in 1.518703ms
2021/01/07 14:53:32 debug out: {"http_request":"http://www.example.com","http_request_headers":{"Accept":["text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"],"Accept-Language":["en-US;q=0.8,en;q=0.5"],"User-Agent":["Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.198 Safari/537.36"]},"tcp_connect":["93.184.216.34:80","[2606:2800:220:1:248:1893:25c8:1946]:80"]}
2021/01/07 14:53:32 debug > POST https://test-helper.ooni.org
2021/01/07 14:53:32 debug > Content-Type: application/json
2021/01/07 14:53:32 debug > Host: test-helper.ooni.org
2021/01/07 14:53:32 debug > User-Agent: oohelper/0.22.0-alpha.4 ooniprobe-engine/0.22.0-alpha.4
2021/01/07 14:53:32 debug >                        
2021/01/07 14:53:32 debug resolve test-helper.ooni.org...
2021/01/07 14:53:32 debug resolve test-helper.ooni.org... ([], dns_nxdomain_error) in 1.182931ms
2021/01/07 14:53:32 debug < dns_nxdomain_error     
panic: client.Do failed: Post "https://test-helper.ooni.org": dns_nxdomain_error

goroutine 1 [running]:
github.com/ooni/probe-engine/internal/runtimex.PanicOnError(...)
	/Users/sbs/src/github.com/ooni/probe-engine/internal/runtimex/runtimex.go:10
main.main()
	/Users/sbs/src/github.com/ooni/probe-engine/cmd/oohelper/oohelper.go:44 +0x53c
```

My diagnosis: https://test-helper.ooni.org is misconfigured.

**Comment by bassosimone** [comment]
Fixed by @FedericoCeratto, thanks!
