### ISSUE TITLE
probe-engine crash with x86 simulator

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#399]
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xbe9d96bc]
goroutine 5 [running]:
runtime/internal/atomic.Xadd64(0x8a9885f4, 0x1, 0x0, 0xbe9e31e7, 0x8a80e310)
	/Users/runner/hostedtoolcache/go/1.14.0/x64/src/runtime/internal/atomic/asm_386.s:105 +0xc
github.com/ooni/probe-engine.(*Session).queryBouncer(0x8a9885b0, 0xbf54ac60, 0x8a8a6010, 0x8a842cb0, 0x8a85a380, 0x0)
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/session.go:485 +0x45
github.com/ooni/probe-engine.(*Session).maybeLookupCollectors(0x8a9885b0, 0xbf54ac60, 0x8a8a6010, 0x0, 0xbf23bc65)
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/session.go:425 +0x94
github.com/ooni/probe-engine.(*Session).maybeLookupBackends(0x8a9885b0, 0xbf54ac60, 0x8a8a6010, 0xbf481a80, 0x8a80e300)
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/session.go:413 +0x32
github.com/ooni/probe-engine.(*Session).MaybeLookupBackends(...)
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/session.go:198
github.com/ooni/probe-engine/oonimkall.(*runner).Run(0x8a842fc4, 0xbf54ac40, 0x8a8581e0)
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/oonimkall/runner.go:146 +0x1805
github.com/ooni/probe-engine/oonimkall.StartTask.func1(0x8a858200, 0x8a82a590, 0x8a878000, 0xbf54ac40, 0x8a8581e0)
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/oonimkall/task.go:48 +0x120
created by github.com/ooni/probe-engine/oonimkall.StartTask
	/Users/runner/runners/2.165.2/work/probe-engine/probe-engine/oonimkall/task.go:44 +0x199
Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 8567 (AsyncTask #1), pid 8460 (atory.ooniprobe)
```

**Comment by bassosimone** [comment]
This looks very much like https://github.com/ooni/probe-engine/issues/355, except that this time the semantics of accessing the pointer atomically looks really really really legit.

It seems I should probably consider the following `sync/atomic` [issue](https://golang.org/pkg/sync/atomic/#pkg-note-BUG):

> On ARM, x86-32, and 32-bit MIPS, it is the caller's responsibility to arrange for 64-bit alignment of 64-bit words accessed atomically. The first word in a variable or in an allocated struct, array, or slice can be relied upon to be 64-bit aligned.

The first step is checking whether moving the atomic variable fixes the issue. Then, if that is the case, we either always using atomic with 32 bits or we refactor the code by moving variables.

**Comment by bassosimone** [comment]
Indeed, https://github.com/ooni/probe-engine/commit/a951e11c4b131643d4ddb3291a6835e9eaf3ad6a fixes the issue. It stems that we need to refactor the code to take this risk into account (either in Sprint 8 or Sprint 9).

**Comment by bassosimone** [comment]
Fixed in https://github.com/ooni/probe-engine/pull/414. Both me and @lorenzoPrimi have verified that the crash is gone when using code in https://github.com/ooni/probe-engine/pull/414 with x86.
