### ISSUE TITLE
psiphon: checkptr: unsafe pointer conversion

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#486]
When running `go test -race ./...` at `v0.9.0-1-g72c12b0`, I experienced this crash:

```
fatal error: checkptr: unsafe pointer conversion

goroutine 51 [running]:
runtime.throw(0x1516c64, 0x23)
	/usr/lib/golang/src/runtime/panic.go:1112 +0x72 fp=0xc0001d5010 sp=0xc0001d4fe0 pc=0x463002
runtime.checkptrAlignment(0xc000415150, 0x147c5c0, 0x1)
	/usr/lib/golang/src/runtime/checkptr.go:18 +0xb7 fp=0xc0001d5040 sp=0xc0001d5010 pc=0x434647
github.com/Psiphon-Labs/bolt.(*Bucket).write(0xc0001d51b8, 0x0, 0x0, 0x0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/bolt@v0.0.0-20200203172706-f3d58e369264/bucket.go:626 +0x15c fp=0xc0001d50a8 sp=0xc0001d5040 pc=0xb5f42c
github.com/Psiphon-Labs/bolt.(*Bucket).CreateBucket(0xc0001202b8, 0x1de1d68, 0xd, 0xd, 0x0, 0xc0001326f0, 0xc0001c0ff0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/bolt@v0.0.0-20200203172706-f3d58e369264/bucket.go:188 +0x465 fp=0xc0001d5268 sp=0xc0001d50a8 pc=0xb5b995
github.com/Psiphon-Labs/bolt.(*Bucket).CreateBucketIfNotExists(0xc0001202b8, 0x1de1d68, 0xd, 0xd, 0x0, 0xc000216ba0, 0xc0001d5320)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/bolt@v0.0.0-20200203172706-f3d58e369264/bucket.go:206 +0x5e fp=0xc0001d52d0 sp=0xc0001d5268 pc=0xb5bd3e
github.com/Psiphon-Labs/bolt.(*Tx).CreateBucketIfNotExists(...)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/bolt@v0.0.0-20200203172706-f3d58e369264/tx.go:115
github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon.tryDatastoreOpenDB.func3(0xc0001202a0, 0x1, 0xc0001202a0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/psiphon-tunnel-core@v2.0.11-0.20200403181014-fcdf8913c6d5+incompatible/psiphon/dataStore_bolt.go:138 +0x3d7 fp=0xc0001d5470 sp=0xc0001d52d0 pc=0x10b67c7
github.com/Psiphon-Labs/bolt.(*DB).Update(0xc000216a00, 0x1537a50, 0x0, 0x0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/bolt@v0.0.0-20200203172706-f3d58e369264/db.go:637 +0xec fp=0xc0001d5518 sp=0xc0001d5470 pc=0xb691ac
github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon.tryDatastoreOpenDB(0xc000045440, 0x5c, 0x0, 0x0, 0x0, 0x0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/psiphon-tunnel-core@v2.0.11-0.20200403181014-fcdf8913c6d5+incompatible/psiphon/dataStore_bolt.go:121 +0x21d fp=0xc0001d5670 sp=0xc0001d5518 pc=0x10580bd
github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon.datastoreOpenDB(0xc000045440, 0x5c, 0x5c, 0x1, 0x0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/psiphon-tunnel-core@v2.0.11-0.20200403181014-fcdf8913c6d5+incompatible/psiphon/dataStore_bolt.go:63 +0xc6 fp=0xc0001d56e0 sp=0xc0001d5670 pc=0x1057df6
github.com/Psiphon-Labs/psiphon-tunnel-core/psiphon.OpenDataStore(0xc000139100, 0x1, 0x0)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/psiphon-tunnel-core@v2.0.11-0.20200403181014-fcdf8913c6d5+incompatible/psiphon/dataStore.go:72 +0x83 fp=0xc0001d5740 sp=0xc0001d56e0 pc=0x1051ba3
github.com/Psiphon-Labs/psiphon-tunnel-core/ClientLibrary/clientlib.StartTunnel(0x16b98e0, 0xc0004ee240, 0xc0003cc000, 0x756, 0xe00, 0x0, 0x0, 0xc00044c160, 0x0, 0x0, ...)
	/home/sbs/go/pkg/mod/github.com/!psiphon-!labs/psiphon-tunnel-core@v2.0.11-0.20200403181014-fcdf8913c6d5+incompatible/ClientLibrary/clientlib/clientlib.go:173 +0x212 fp=0xc0001d59c0 sp=0xc0001d5740 pc=0x10c1e22
github.com/ooni/probe-engine/experiment/psiphon.(*runner).starttunnel(...)
	/home/sbs/src/github.com/ooni/probe-engine/experiment/psiphon/psiphon.go:104
github.com/ooni/probe-engine/experiment/psiphon.(*runner).run(0xc0004ee2a0, 0x16b98e0, 0xc0004ee240, 0x7f5e89dc8130, 0x1e8de80, 0xc00016dc58, 0x0, 0x0)
	/home/sbs/src/github.com/ooni/probe-engine/experiment/psiphon/psiphon.go:164 +0x4e1 fp=0xc0001d5b70 sp=0xc0001d59c0 pc=0x12fbf61
github.com/ooni/probe-engine/experiment/psiphon.(*measurer).Run(0xc00013a5e0, 0x16b98e0, 0xc0004ee240, 0x16c9a80, 0xc000126000, 0xc00016dd28, 0x16b0b80, 0xc00013a5f0, 0x1dde414, 0x26)
	/home/sbs/src/github.com/ooni/probe-engine/experiment/psiphon/psiphon.go:227 +0x7c3 fp=0xc0001d5c80 sp=0xc0001d5b70 pc=0x12fce33
github.com/ooni/probe-engine/experiment/psiphon.TestIntegration(0xc0001ba240)
	/home/sbs/src/github.com/ooni/probe-engine/experiment/psiphon/psiphon_test.go:150 +0x28b fp=0xc0001d5ed0 sp=0xc0001d5c80 pc=0x12ffc1b
testing.tRunner(0xc0001ba240, 0x1538888)
	/usr/lib/golang/src/testing/testing.go:992 +0x1ec fp=0xc0001d5fd0 sp=0xc0001d5ed0 pc=0x5ba1bc
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc0001d5fd8 sp=0xc0001d5fd0 pc=0x496ce1
created by testing.(*T).Run
	/usr/lib/golang/src/testing/testing.go:1043 +0x661
```

This seems to be related to Psiphon's bolt fork.

**Comment by bassosimone** [comment]
It seems this issue has been solved, since I could run `go test -race ./...` today, after updating to the latest version of the psiphon's staging-client branch as of today. I'll assign this issue to the next sprint for the follow-up.

**Comment by bassosimone** [comment]
I actually spent time doing this, so I am stealing effort from another task to make the balance even.
