### ISSUE TITLE
github actions failure to investigate

### ISSUE THREAD

**Issue by bassosimone** [ooni/probe-engine#874]
```
2020-08-24T13:40:14.5198718Z --- FAIL: TestMeasureWithCancelledContext (3.48s)
2020-08-24T13:40:14.5198900Z panic: runtime error: invalid memory address or nil pointer dereference [recovered]
2020-08-24T13:40:14.5199087Z 	panic: runtime error: invalid memory address or nil pointer dereference
2020-08-24T13:40:14.5199357Z [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x13ba6c4]
2020-08-24T13:40:14.5199447Z 
2020-08-24T13:40:14.5199610Z goroutine 243 [running]:
2020-08-24T13:40:14.5199810Z testing.tRunner.func1.1(0x15118e0, 0x224e390)
2020-08-24T13:40:14.5238646Z 	/opt/hostedtoolcache/go/1.14.7/x64/src/testing/testing.go:988 +0x452
2020-08-24T13:40:14.5238874Z testing.tRunner.func1(0xc000404000)
2020-08-24T13:40:14.5239115Z 	/opt/hostedtoolcache/go/1.14.7/x64/src/testing/testing.go:991 +0x600
2020-08-24T13:40:14.5239300Z panic(0x15118e0, 0x224e390)
2020-08-24T13:40:14.5239538Z 	/opt/hostedtoolcache/go/1.14.7/x64/src/runtime/panic.go:975 +0x3e3
2020-08-24T13:40:14.5240492Z github.com/ooni/probe-engine/experiment/webconnectivity_test.TestMeasureWithCancelledContext(0xc000404000)
2020-08-24T13:40:14.5241097Z 	/home/runner/work/probe-engine/probe-engine/experiment/webconnectivity/webconnectivity_test.go:75 +0x414
2020-08-24T13:40:14.5241311Z testing.tRunner(0xc000404000, 0x16e1598)
2020-08-24T13:40:14.5241552Z 	/opt/hostedtoolcache/go/1.14.7/x64/src/testing/testing.go:1039 +0x1ec
2020-08-24T13:40:14.5241736Z created by testing.(*T).Run
2020-08-24T13:40:14.5241973Z 	/opt/hostedtoolcache/go/1.14.7/x64/src/testing/testing.go:1090 +0x701
2020-08-24T13:40:14.5242403Z FAIL	github.com/ooni/probe-engine/experiment/webconnectivity	23.586s
```

See https://github.com/ooni/probe-engine/runs/1021797583

**Comment by bassosimone** [comment]
Also:

```
2020-08-25T06:50:40.6808792Z 2020/08/25 06:49:29  info [  0.0%] stunreachability: measuring: stun.l.google.com:19302...
2020-08-25T06:50:40.6808988Z 2020/08/25 06:49:40  info [100.0%] stunreachability: measuring: stun.l.google.com:19302... done
2020-08-25T06:50:40.6809743Z ##[error]    stunreachability_test.go:39: generic_timeout_error
2020-08-25T06:50:40.6810428Z --- FAIL: TestIntegrationRun (10.84s)
```

See https://github.com/ooni/probe-engine/runs/1025195308

**Comment by bassosimone** [comment]
The first failure (https://github.com/ooni/probe-engine/issues/874#issue-684690100) is actually fine: it just means that a specific assertion was not met and the code was rather undefensive in the tests, which is fine.

**Comment by bassosimone** [comment]
The initial error happened again: https://github.com/ooni/probe-engine/runs/1026321011

**Comment by bassosimone** [comment]
Not happening very often, let us postpone this to the next sprint.

**Comment by bassosimone** [comment]
Moving to next sprint and transferring the effort points to https://github.com/ooni/probe-engine/issues/893

**Comment by bassosimone** [comment]
Splitting this issue in https://github.com/ooni/probe-engine/issues/1096 and in a failure that actually we don't need to fix because it's just happening randomly because of connectivity fluctuations.
